name: "Run Auto-Semver"
description: "Github Action for RBN Auto Semver by Branch tool"
author: RightBrain-Networks
inputs:
  mode:
    description: 'Run in either `get`, `check`, or `update` mode'
    required: false
    default: set
outputs:
  RETURN_STATUS:
    description: Return status of AutoSemver
  SEMVER_NEW_VERSION:
    description: New version set by AutoSemver
  VERSION:
    description: Version returned by AutoSemver
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.mode }}
branding:
  icon: chevrons-up
  color: blue